import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "./page.module.css";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const mainnets = [
    { name: 'Ethereum', id: 1 },
    { name: 'Binance Smart Chain', id: 2 },
    { name: 'Polygon', id: 3 },
    // Add more mainnets as needed
  ];
  return (
    <main className={styles.main}>
      <div className="navbar">
        <h1>token</h1>
      </div>
      <div className="div1">
        <div className="div2">
          <h1>Contract metadata</h1>
          <h3>Settings</h3>
        </div>
        <div className="tag">
          <div className="tag1">
            <label for="text-field-1">Name</label>
            <input type="text" id="text-field-1" name="text-field-1" />
            <label for="text-field-2">symbol</label>
            <input type="text" id="text-field-2" name="text-field-2" />
            <label for="text-field-3">Description</label>
            <input type="text" id="text-field-3" name="text-field-3" />
          </div>
          <div>
            <br></br>
            <label for="image-input">Select Image:</label>
            <input type="file" id="image-input" name="image-input" />
          </div>
        </div>
      </div>
      <div className="div3">
        <h1>Payout Settings</h1>
        <h3>Where should any funds generated by this contract flow to</h3>

        <h1>Primary Sales</h1>
        <h3>
          Determine the address that should recieve the revenue from initial
          sales of the assets
        </h3>
        <h1>Recipient Address</h1>
        <input type="text"></input>
      </div>
      <div>
        <h1>Network/Chain</h1>
        <h4>
            Select a network to deploy this contract on.We recommend starting
            with a testnet
          </h4>
          <br/>
        <div className="div4">
        
        
          <input type="checkbox" />
          <h4>Add this to the dashboard</h4>
        </div>
      </div>
      <div className="mainnets-dropdown">
      <select>
        {mainnets.map((mainnet) => (
          <option key={mainnet.id} value={mainnet.id}>
            {mainnet.name}
          </option>
        ))}
      </select>
      <button className="blue-button">Deploy</button>
      <br />
      <button type="button" class="btn">Configure networks</button>
      <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Default</button>
    </div>
    </main>
  );
}



